"""
Integration tests for mapping field updates with child action propagation

Tests the end-to-end behavior when updating field actions through MappingHandler.set_field()
to ensure that child action propagation is properly integrated.
"""

import unittest
from unittest.mock import Mock, patch
from structure_comparer.handler.mapping import MappingHandler
from structure_comparer.handler.project import ProjectsHandler
from structure_comparer.model.mapping import MappingFieldMinimal
from structure_comparer.action import Action
from structure_comparer.data.project import Project
from structure_comparer.data.mapping import Mapping
from structure_comparer.manual_entries import ManualEntries


class TestMappingFieldUpdateWithPropagation(unittest.TestCase):
    
    def setUp(self):
        """Set up test dependencies"""
        self.project_handler = Mock(spec=ProjectsHandler)
        self.mapping_handler = MappingHandler(self.project_handler)
        
        # Mock project
        self.mock_project = Mock(spec=Project)
        self.project_handler._get.return_value = self.mock_project
        
        # Mock mapping
        self.mock_mapping = Mock(spec=Mapping)
        self.mock_project.mappings = {"test-mapping-id": self.mock_mapping}
        
        # Mock manual entries
        self.mock_manual_entries = Mock(spec=ManualEntries)
        self.mock_project.manual_entries = self.mock_manual_entries
        
        # Mock field hierarchy for test
        self.mock_fields = {}
        self._setup_test_fields()
        self.mock_mapping.fields = self.mock_fields
        
    def _setup_test_fields(self):
        """Setup test field hierarchy"""
        # Parent field
        parent_field = Mock()
        parent_field.name = "Practitioner.meta.tag"
        parent_field.actions_allowed = [Action.USE, Action.NOT_USE, Action.EMPTY, Action.MANUAL]
        self.mock_fields["Practitioner.meta.tag"] = parent_field
        
        # Child fields (should be auto-generated by propagation)
        child_fields = [
            "Practitioner.meta.tag:Origin",
            "Practitioner.meta.tag:profile:forProfile"
        ]
        for child_name in child_fields:
            child_field = Mock()
            child_field.name = child_name
            child_field.actions_allowed = [Action.USE, Action.NOT_USE, Action.EMPTY, Action.MANUAL]
            self.mock_fields[child_name] = child_field
    
    def _setup_manual_entries_mock(self, initial_fields=None):
        """Setup manual entries mock with dictionary-like behavior"""
        from structure_comparer.model.manual_entries import ManualEntriesMapping
        
        manual_entries_mapping = {}
        if initial_fields:
            manual_entries_mapping["test-mapping-id"] = Mock(spec=ManualEntriesMapping)
            manual_entries_mapping["test-mapping-id"].fields = initial_fields
        
        self.mock_manual_entries.get.side_effect = lambda mapping_id: manual_entries_mapping.get(mapping_id)
        self.mock_manual_entries.__setitem__ = lambda key, value: manual_entries_mapping.__setitem__(key, value)
        
        # Mock to_dict and from_dict for propagation
        def to_dict():
            return {
                "entries": [{
                    "id": "test-mapping-id",
                    "fields": list(initial_fields.values()) if initial_fields else []
                }]
            }
        
        def from_dict(data):
            # Update the mock with new data
            if data and "entries" in data:
                for entry in data["entries"]:
                    if entry["id"] == "test-mapping-id":
                        manual_entries_mapping["test-mapping-id"] = Mock()
                        manual_entries_mapping["test-mapping-id"].fields = {
                            field["name"]: field for field in entry["fields"]
                        }
        
        self.mock_manual_entries.to_dict = to_dict
        self.mock_manual_entries.from_dict = from_dict
        self.mock_manual_entries.write = Mock()
        
        return manual_entries_mapping
    
    @patch('structure_comparer.child_action_propagation.propagate_parent_actions_to_children')
    def test_set_field_calls_propagation(self, mock_propagation):
        """Test that set_field calls child action propagation"""
        # Setup
        self._setup_manual_entries_mock()
        mock_propagation.return_value = self.mock_manual_entries.to_dict()
        
        field_input = MappingFieldMinimal(action=Action.NOT_USE)
        
        # Act
        result = self.mapping_handler.set_field(
            "test-project",
            "test-mapping-id", 
            "Practitioner.meta.tag", 
            field_input
        )
        
        # Assert
        self.assertIsNotNone(result)
        self.assertEqual(result.action, Action.NOT_USE)
        
        # Verify propagation was called
        mock_propagation.assert_called_once()
        call_args = mock_propagation.call_args
        self.assertEqual(call_args[0][1], self.mock_project)  # project parameter
        self.assertEqual(call_args[0][2], "test-mapping-id")  # mapping_id parameter
    
    def test_set_field_with_not_use_action(self):
        """Test setting NOT_USE action creates proper field update"""
        # Setup
        self._setup_manual_entries_mock()
        
        field_input = MappingFieldMinimal(action=Action.NOT_USE)
        
        # Mock the propagation to return child fields
        with patch('structure_comparer.child_action_propagation.propagate_parent_actions_to_children') as mock_prop:
            mock_prop.return_value = {
                "entries": [{
                    "id": "test-mapping-id",
                    "fields": [
                        {
                            "name": "Practitioner.meta.tag",
                            "action": "not_use",
                            "auto_generated": False
                        },
                        {
                            "name": "Practitioner.meta.tag:Origin", 
                            "action": "not_use",
                            "auto_generated": True,
                            "inherited_from": "Practitioner.meta.tag"
                        },
                        {
                            "name": "Practitioner.meta.tag:profile:forProfile",
                            "action": "not_use", 
                            "auto_generated": True,
                            "inherited_from": "Practitioner.meta.tag"
                        }
                    ]
                }]
            }
            
            # Act
            result = self.mapping_handler.set_field(
                "test-project",
                "test-mapping-id",
                "Practitioner.meta.tag",
                field_input
            )
            
            # Assert
            self.assertEqual(result.action, Action.NOT_USE)
            self.assertEqual(result.name, "Practitioner.meta.tag")
            
            # Verify propagation was called with correct data
            mock_prop.assert_called_once()
    
    def test_set_field_with_copy_from_action(self):
        """Test setting COPY_FROM action with target field"""
        # Setup
        self._setup_manual_entries_mock()
        
        field_input = MappingFieldMinimal(
            action=Action.COPY_FROM,
            other="SomeTargetField"
        )
        
        # Mock target field
        target_field = Mock()
        target_field.name = "SomeTargetField"
        self.mock_fields["SomeTargetField"] = target_field
        
        with patch('structure_comparer.child_action_propagation.propagate_parent_actions_to_children') as mock_prop:
            mock_prop.return_value = self.mock_manual_entries.to_dict()
            
            # Act
            result = self.mapping_handler.set_field(
                "test-project",
                "test-mapping-id",
                "Practitioner.meta.tag",
                field_input
            )
            
            # Assert
            self.assertEqual(result.action, Action.COPY_FROM)
            self.assertEqual(result.other, "SomeTargetField")
            
            # Verify propagation was called
            mock_prop.assert_called_once()
    
    @patch('structure_comparer.child_action_propagation.propagate_parent_actions_to_children')
    def test_propagation_failure_does_not_break_field_update(self, mock_propagation):
        """Test that propagation failure doesn't break the field update"""
        # Setup
        self._setup_manual_entries_mock()
        mock_propagation.side_effect = Exception("Propagation failed")
        
        field_input = MappingFieldMinimal(action=Action.EMPTY)
        
        # Act (should not raise exception)
        result = self.mapping_handler.set_field(
            "test-project",
            "test-mapping-id",
            "Practitioner.meta.tag",
            field_input
        )
        
        # Assert - field update should still succeed
        self.assertIsNotNone(result)
        self.assertEqual(result.action, Action.EMPTY)
    
    def test_set_field_with_extension_and_remark(self):
        """Test setting EXTENSION action with custom remark"""
        # Setup
        self._setup_manual_entries_mock()
        
        field_input = MappingFieldMinimal(
            action=Action.EXTENSION,
            remark="Custom extension handling"
        )
        
        with patch('structure_comparer.child_action_propagation.propagate_parent_actions_to_children') as mock_prop:
            mock_prop.return_value = self.mock_manual_entries.to_dict()
            
            # Act
            result = self.mapping_handler.set_field(
                "test-project",
                "test-mapping-id",
                "Practitioner.meta.tag",
                field_input
            )
            
            # Assert
            self.assertEqual(result.action, Action.EXTENSION)
            self.assertEqual(result.remark, "Custom extension handling")
            
            # Verify propagation was called
            mock_prop.assert_called_once()


if __name__ == '__main__':
    unittest.main()